FROM apache/airflow:3.3.2

USER airflow

# 공식 이미지 -> 2.x 여러 컨테이너(서비스들)가 필요
#           -> 3.x allinone -> 1개의 서비스에 모두 포함됨, db만 postgresql 공용
# 추가 설치 패키지 때문에 Dockerfile 구성
COPY requirements.txt /requirements.txt